server:
  port: 8080

logging:
  config: classpath:logback-spring.xml

spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    fulltext:
      jdbc-url: jdbc:mysql://localhost:3306/full_text?useUnicode=true
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 10
      maxWait: 60000
      maxIdle: 20
      minIdle: 10
      remove-abandoned: true
      remove-abandoned-timeout: 300
      validation-query: SELECT 1
      validation-interval: 30000
      test-on-borrow: true
      test-on-return: false
      default-auto-commit: true
      max-age: 30000